<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SgdsSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'goal_number' => '1',
                'goal_name' => 'Desa Tanpa Kemiskinan',
                'description' => 'Mengurangi angka kemiskinan di Kampung Dalam.',
                'target_code' => '1.1',
                'target_description' => 'Menghapus kemiskinan ekstrem di seluruh desa.',
                'indicator_code' => '1.1.1',
                'indicator_description' => 'Persentase penduduk miskin di Kampung Dalam.',
                'unit' => '%',
                'year' => '2024',
                'value' => 12.50,
                'source' => 'BPS Kabupaten Siak',
                'icon' => 'icons/goal1.png',
            ],
            [
                'goal_number' => '2',
                'goal_name' => 'Desa Tanpa Kelaparan',
                'description' => 'Menjamin ketersediaan pangan di Kampung Dalam.',
                'target_code' => '2.1',
                'target_description' => 'Mengakhiri kelaparan dan gizi buruk.',
                'indicator_code' => '2.1.1',
                'indicator_description' => 'Persentase keluarga rawan pangan.',
                'unit' => '%',
                'year' => '2024',
                'value' => 8.30,
                'source' => 'Dinas Ketahanan Pangan',
                'icon' => 'icons/goal2.png',
            ],
            [
                'goal_number' => '3',
                'goal_name' => 'Desa Sehat dan Sejahtera',
                'description' => 'Meningkatkan derajat kesehatan masyarakat desa.',
                'target_code' => '3.2',
                'target_description' => 'Mengurangi angka kematian ibu dan bayi.',
                'indicator_code' => '3.2.1',
                'indicator_description' => 'Jumlah bayi lahir sehat.',
                'unit' => 'orang',
                'year' => '2024',
                'value' => 230,
                'source' => 'Puskesmas Siak',
                'icon' => 'icons/goal3.png',
            ],
            [
                'goal_number' => '4',
                'goal_name' => 'Pendidikan Desa Berkualitas',
                'description' => 'Akses pendidikan yang merata dan berkualitas.',
                'target_code' => '4.1',
                'target_description' => 'Meningkatkan angka partisipasi sekolah.',
                'indicator_code' => '4.1.1',
                'indicator_description' => 'Angka partisipasi sekolah usia 7-18 tahun.',
                'unit' => '%',
                'year' => '2024',
                'value' => 96.00,
                'source' => 'Dinas Pendidikan Siak',
                'icon' => 'icons/goal4.png',
            ],
            [
                'goal_number' => '5',
                'goal_name' => 'Keterlibatan Perempuan Desa',
                'description' => 'Pemberdayaan perempuan dalam pembangunan desa.',
                'target_code' => '5.5',
                'target_description' => 'Meningkatkan keterwakilan perempuan.',
                'indicator_code' => '5.5.1',
                'indicator_description' => 'Persentase perempuan di lembaga desa.',
                'unit' => '%',
                'year' => '2024',
                'value' => 35.00,
                'source' => 'Pemdes Kampung Dalam',
                'icon' => 'icons/goal5.png',
            ],
            [
                'goal_number' => '6',
                'goal_name' => 'Desa Layak Air Bersih',
                'description' => 'Akses air bersih dan sanitasi layak.',
                'target_code' => '6.1',
                'target_description' => 'Meningkatkan akses rumah tangga terhadap air bersih.',
                'indicator_code' => '6.1.1',
                'indicator_description' => 'Persentase keluarga dengan akses air bersih.',
                'unit' => '%',
                'year' => '2024',
                'value' => 89.00,
                'source' => 'PDAM Siak',
                'icon' => 'icons/goal6.png',
            ],
            [
                'goal_number' => '7',
                'goal_name' => 'Desa Berenergi Bersih',
                'description' => 'Pemanfaatan energi terbarukan.',
                'target_code' => '7.1',
                'target_description' => 'Meningkatkan akses energi modern.',
                'indicator_code' => '7.1.1',
                'indicator_description' => 'Persentase rumah tangga menggunakan listrik PLN.',
                'unit' => '%',
                'year' => '2024',
                'value' => 98.50,
                'source' => 'PLN Ranting Siak',
                'icon' => 'icons/goal7.png',
            ],
            [
                'goal_number' => '8',
                'goal_name' => 'Pertumbuhan Ekonomi Desa',
                'description' => 'Meningkatkan ekonomi produktif desa.',
                'target_code' => '8.3',
                'target_description' => 'Mendukung UMKM desa.',
                'indicator_code' => '8.3.1',
                'indicator_description' => 'Jumlah UMKM aktif di Kampung Dalam.',
                'unit' => 'unit',
                'year' => '2024',
                'value' => 120,
                'source' => 'Diskop UKM Siak',
                'icon' => 'icons/goal8.png',
            ],
            [
                'goal_number' => '9',
                'goal_name' => 'Infrastruktur dan Inovasi Desa',
                'description' => 'Pembangunan infrastruktur dasar.',
                'target_code' => '9.1',
                'target_description' => 'Meningkatkan akses jalan desa.',
                'indicator_code' => '9.1.1',
                'indicator_description' => 'Persentase jalan desa dalam kondisi baik.',
                'unit' => '%',
                'year' => '2024',
                'value' => 75.00,
                'source' => 'Dinas PU Siak',
                'icon' => 'icons/goal9.png',
            ],
            [
                'goal_number' => '10',
                'goal_name' => 'Mengurangi Ketimpangan Desa',
                'description' => 'Mendorong kesetaraan pembangunan desa.',
                'target_code' => '10.2',
                'target_description' => 'Meningkatkan inklusi sosial dan ekonomi.',
                'indicator_code' => '10.2.1',
                'indicator_description' => 'Rasio gini desa.',
                'unit' => 'rasio',
                'year' => '2024',
                'value' => 0.37,
                'source' => 'BPS Siak',
                'icon' => 'icons/goal10.png',
            ],
            [
                'goal_number' => '11',
                'goal_name' => 'Desa Ramah Lingkungan',
                'description' => 'Membangun permukiman desa yang berkelanjutan.',
                'target_code' => '11.1',
                'target_description' => 'Meningkatkan kualitas lingkungan permukiman.',
                'indicator_code' => '11.1.1',
                'indicator_description' => 'Jumlah rumah tidak layak huni yang direhab.',
                'unit' => 'unit',
                'year' => '2024',
                'value' => 35,
                'source' => 'Dinas Perkim Siak',
                'icon' => 'icons/goal11.png',
            ],
            [
                'goal_number' => '12',
                'goal_name' => 'Konsumsi dan Produksi Desa',
                'description' => 'Mendorong pola konsumsi yang ramah lingkungan.',
                'target_code' => '12.4',
                'target_description' => 'Mengurangi timbunan sampah rumah tangga.',
                'indicator_code' => '12.4.1',
                'indicator_description' => 'Persentase sampah rumah tangga yang terkelola.',
                'unit' => '%',
                'year' => '2024',
                'value' => 64.00,
                'source' => 'DLHK Siak',
                'icon' => 'icons/goal12.png',
            ],
            [
                'goal_number' => '13',
                'goal_name' => 'Tanggap Perubahan Iklim',
                'description' => 'Mitigasi dan adaptasi iklim desa.',
                'target_code' => '13.1',
                'target_description' => 'Mengurangi dampak perubahan iklim.',
                'indicator_code' => '13.1.1',
                'indicator_description' => 'Jumlah kegiatan mitigasi iklim di desa.',
                'unit' => 'kegiatan',
                'year' => '2024',
                'value' => 7,
                'source' => 'DLHK Siak',
                'icon' => 'icons/goal13.png',
            ],
            [
                'goal_number' => '14',
                'goal_name' => 'Ekosistem Perairan Desa',
                'description' => 'Melestarikan sungai dan perairan desa.',
                'target_code' => '14.2',
                'target_description' => 'Mengurangi pencemaran sungai.',
                'indicator_code' => '14.2.1',
                'indicator_description' => 'Kualitas air sungai.',
                'unit' => 'indeks',
                'year' => '2024',
                'value' => 78.00,
                'source' => 'DLHK Siak',
                'icon' => 'icons/goal14.png',
            ],
            [
                'goal_number' => '15',
                'goal_name' => 'Ekosistem Daratan Desa',
                'description' => 'Perlindungan hutan dan lahan.',
                'target_code' => '15.1',
                'target_description' => 'Menurunkan laju deforestasi.',
                'indicator_code' => '15.1.1',
                'indicator_description' => 'Luas lahan hijau desa.',
                'unit' => 'ha',
                'year' => '2024',
                'value' => 320.00,
                'source' => 'DLHK Siak',
                'icon' => 'icons/goal15.png',
            ],
            [
                'goal_number' => '16',
                'goal_name' => 'Kelembagaan Desa Dinamis',
                'description' => 'Meningkatkan tata kelola desa yang partisipatif.',
                'target_code' => '16.6',
                'target_description' => 'Meningkatkan transparansi lembaga desa.',
                'indicator_code' => '16.6.1',
                'indicator_description' => 'Jumlah musyawarah desa per tahun.',
                'unit' => 'kali',
                'year' => '2024',
                'value' => 12,
                'source' => 'Pemdes Kampung Dalam',
                'icon' => 'icons/goal16.png',
            ],
            [
                'goal_number' => '17',
                'goal_name' => 'Kemitraan Desa',
                'description' => 'Kerja sama antar desa dan pihak luar.',
                'target_code' => '17.7',
                'target_description' => 'Meningkatkan jumlah kerja sama desa.',
                'indicator_code' => '17.7.1',
                'indicator_description' => 'Jumlah MoU desa dengan pihak eksternal.',
                'unit' => 'MoU',
                'year' => '2024',
                'value' => 5,
                'source' => 'Pemdes Kampung Dalam',
                'icon' => 'icons/goal17.png',
            ],
            [
                'goal_number' => '18',
                'goal_name' => 'Budaya Desa Adaptif',
                'description' => 'Pelestarian dan adaptasi budaya lokal.',
                'target_code' => '18.1',
                'target_description' => 'Meningkatkan kegiatan budaya desa.',
                'indicator_code' => '18.1.1',
                'indicator_description' => 'Jumlah kegiatan budaya per tahun.',
                'unit' => 'kegiatan',
                'year' => '2024',
                'value' => 15,
                'source' => 'Dinas Pariwisata Siak',
                'icon' => 'icons/goal18.png',
            ],
        ];

        DB::table('sgds')->insert($data);
    }
}
