<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Umkm;

class UmkmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $umkmData = [
            [
                'business_name' => 'Warung Makan Sari Rasa',
                'owner_name' => 'Ibu Siti Aminah',
                'nik' => '1471234567890001',
                'category' => 'kuliner',
                'description' => 'Warung makan yang menyajikan masakan khas Melayu dengan cita rasa autentik. Spesialisasi nasi lemak, rendang, dan gulai ikan patin. Menggunakan bumbu tradisional yang diracik sendiri dengan resep turun temurun.',
                'featured_image' => 'umkm/warung-sari-rasa.jpg',
                'product_images' => json_encode([
                    'umkm/sari-rasa-1.jpg',
                    'umkm/sari-rasa-2.jpg',
                    'umkm/sari-rasa-3.jpg'
                ]),
                'address' => 'Jl. Raya Kampung Dalam No. 15, RT 02/RW 01',
                'phone' => '081234567890',
                'whatsapp' => '081234567890',
                'email' => 'saririasa@gmail.com',
                'instagram' => '@warungsarirasa',
                'facebook' => 'Warung Sari Rasa',
                'website' => null,
                'products' => 'Nasi Lemak, Rendang Daging, Gulai Ikan Patin, Sambal Terasi, Es Cendol, Teh Tarik, Kopi Kampung',
                'capital' => 25000000.00,
                'monthly_revenue' => 15000000.00,
                'employee_count' => 5,
                'established_date' => '2018-03-15',
                'license_number' => 'SIUP/001/2018',
                'is_active' => true,
            ],
            [
                'business_name' => 'Kerajinan Anyaman Pandan Indah',
                'owner_name' => 'Bapak Ahmad Yusuf',
                'nik' => '1471234567890002',
                'category' => 'kerajinan',
                'description' => 'Usaha kerajinan anyaman dari daun pandan yang menghasilkan berbagai produk seperti tas, topi, dan souvenir khas daerah. Menggunakan teknik anyaman tradisional yang telah diwariskan turun temurun.',
                'featured_image' => 'umkm/anyaman-pandan.jpg',
                'product_images' => json_encode([
                    'umkm/pandan-1.jpg',
                    'umkm/pandan-2.jpg',
                    'umkm/pandan-3.jpg',
                    'umkm/pandan-4.jpg'
                ]),
                'address' => 'Dusun Pandan Wangi RT 02/RW 01',
                'phone' => '081345678901',
                'whatsapp' => '081345678901',
                'email' => 'pandanindah@gmail.com',
                'instagram' => '@anyamanpandanindah',
                'facebook' => 'Kerajinan Pandan Indah',
                'website' => null,
                'products' => 'Tas Anyaman, Topi Pandan, Tempat Pensil, Souvenir, Keranjang, Tikar Pandan, Tempat Tisu',
                'capital' => 15000000.00,
                'monthly_revenue' => 8500000.00,
                'employee_count' => 8,
                'established_date' => '2015-07-20',
                'license_number' => 'IUI/002/2015',
                'is_active' => true,
            ],
            [
                'business_name' => 'Toko Kelontong Berkah Jaya',
                'owner_name' => 'Ibu Ratna Sari',
                'nik' => '1471234567890003',
                'category' => 'perdagangan',
                'description' => 'Toko kelontong lengkap yang melayani kebutuhan sehari-hari masyarakat dengan harga terjangkau dan pelayanan ramah. Menyediakan berbagai kebutuhan pokok dan barang konsumsi.',
                'featured_image' => 'umkm/toko-berkah.jpg',
                'product_images' => json_encode([
                    'umkm/berkah-1.jpg',
                    'umkm/berkah-2.jpg'
                ]),
                'address' => 'Jl. Masjid Kampung Dalam No. 8, RT 01/RW 01',
                'phone' => '081456789012',
                'whatsapp' => '081456789012',
                'email' => 'berkahjaya@gmail.com',
                'instagram' => '@tokoberkahjaya',
                'facebook' => null,
                'website' => null,
                'products' => 'Sembako, Alat Tulis, Obat-obatan, Minuman, Makanan Ringan, Rokok, Pulsa, Token Listrik',
                'capital' => 35000000.00,
                'monthly_revenue' => 12000000.00,
                'employee_count' => 3,
                'established_date' => '2012-01-10',
                'license_number' => 'SIUP/003/2012',
                'is_active' => true,
            ],
            [
                'business_name' => 'Bengkel Motor Jaya Teknik',
                'owner_name' => 'Bapak Edi Susanto',
                'nik' => '1471234567890004',
                'category' => 'jasa',
                'description' => 'Bengkel motor yang melayani service, perbaikan, dan penjualan spare part dengan teknisi berpengalaman. Melayani semua jenis motor dengan garansi perbaikan.',
                'featured_image' => 'umkm/bengkel-jaya.jpg',
                'product_images' => json_encode([
                    'umkm/bengkel-1.jpg',
                    'umkm/bengkel-2.jpg',
                    'umkm/bengkel-3.jpg'
                ]),
                'address' => 'Jl. Raya Kampung Dalam No. 25, RT 03/RW 02',
                'phone' => '081567890123',
                'whatsapp' => '081567890123',
                'email' => 'jayateknik@gmail.com',
                'instagram' => '@bengkeljayateknik',
                'facebook' => 'Bengkel Jaya Teknik',
                'website' => null,
                'products' => 'Service Motor, Ganti Oli, Spare Part, Ban Motor, Aki Motor, Tune Up, Ganti Kampas Rem',
                'capital' => 45000000.00,
                'monthly_revenue' => 10500000.00,
                'employee_count' => 4,
                'established_date' => '2016-05-12',
                'license_number' => 'SIUP/004/2016',
                'is_active' => true,
            ],
            [
                'business_name' => 'Peternakan Ayam Kampung Sejahtera',
                'owner_name' => 'Bapak Hasan Basri',
                'nik' => '1471234567890005',
                'category' => 'pertanian',
                'description' => 'Peternakan ayam kampung yang menghasilkan telur dan daging ayam berkualitas tinggi dengan sistem pemeliharaan tradisional. Ayam dipelihara secara organik tanpa antibiotik.',
                'featured_image' => 'umkm/peternakan-ayam.jpg',
                'product_images' => json_encode([
                    'umkm/ayam-1.jpg',
                    'umkm/ayam-2.jpg',
                    'umkm/ayam-3.jpg'
                ]),
                'address' => 'Dusun Sejahtera RT 03/RW 02',
                'phone' => '081678901234',
                'whatsapp' => '081678901234',
                'email' => 'ayamsejahtera@gmail.com',
                'instagram' => '@ayamsejahtera',
                'facebook' => 'Peternakan Sejahtera',
                'website' => null,
                'products' => 'Telur Ayam Kampung, Daging Ayam, Ayam Hidup, Pupuk Kandang, DOC Ayam Kampung',
                'capital' => 60000000.00,
                'monthly_revenue' => 18000000.00,
                'employee_count' => 6,
                'established_date' => '2019-02-28',
                'license_number' => 'SIUP/005/2019',
                'is_active' => true,
            ],
            [
                'business_name' => 'Salon Kecantikan Cantik Alami',
                'owner_name' => 'Ibu Dewi Lestari',
                'nik' => '1471234567890006',
                'category' => 'jasa',
                'description' => 'Salon kecantikan yang menyediakan layanan perawatan rambut, wajah, dan kuku dengan produk alami dan berkualitas. Menggunakan produk organik untuk hasil yang maksimal.',
                'featured_image' => 'umkm/salon-cantik.jpg',
                'product_images' => json_encode([
                    'umkm/salon-1.jpg',
                    'umkm/salon-2.jpg'
                ]),
                'address' => 'Jl. Melati Kampung Dalam No. 12, RT 01/RW 02',
                'phone' => '081789012345',
                'whatsapp' => '081789012345',
                'email' => 'cantikalami@gmail.com',
                'instagram' => '@cantikalami_salon',
                'facebook' => 'Salon Cantik Alami',
                'website' => null,
                'products' => 'Potong Rambut, Creambath, Facial, Manicure, Pedicure, Hair Spa, Make Up',
                'capital' => 20000000.00,
                'monthly_revenue' => 7500000.00,
                'employee_count' => 3,
                'established_date' => '2020-08-15',
                'license_number' => 'SIUP/006/2020',
                'is_active' => true,
            ],
            [
                'business_name' => 'Tani Organik Hijau Lestari',
                'owner_name' => 'Bapak Bambang Sutrisno',
                'nik' => '1471234567890007',
                'category' => 'pertanian',
                'description' => 'Usaha pertanian organik yang menghasilkan sayuran segar tanpa pestisida dengan sistem hidroponik dan aquaponik. Menggunakan teknologi modern untuk hasil yang optimal.',
                'featured_image' => 'umkm/tani-organik.jpg',
                'product_images' => json_encode([
                    'umkm/organik-1.jpg',
                    'umkm/organik-2.jpg',
                    'umkm/organik-3.jpg',
                    'umkm/organik-4.jpg'
                ]),
                'address' => 'Dusun Hijau RT 01/RW 03',
                'phone' => '081890123456',
                'whatsapp' => '081890123456',
                'email' => 'hijaulestari@gmail.com',
                'instagram' => '@hijaulestari_farm',
                'facebook' => 'Tani Organik Hijau Lestari',
                'website' => 'www.hijaulestari.com',
                'products' => 'Sayuran Organik, Kangkung Hidroponik, Selada, Tomat, Cabai, Bayam, Sawi, Brokoli',
                'capital' => 50000000.00,
                'monthly_revenue' => 13500000.00,
                'employee_count' => 7,
                'established_date' => '2021-01-20',
                'license_number' => 'SIUP/007/2021',
                'is_active' => true,
            ],
            [
                'business_name' => 'Konveksi Busana Muslim Barokah',
                'owner_name' => 'Ibu Nurhayati',
                'nik' => '1471234567890008',
                'category' => 'kerajinan',
                'description' => 'Konveksi yang memproduksi busana muslim berkualitas dengan desain modern dan harga terjangkau untuk segala usia. Menerima pesanan dalam jumlah besar maupun eceran.',
                'featured_image' => 'umkm/konveksi-barokah.jpg',
                'product_images' => json_encode([
                    'umkm/barokah-1.jpg',
                    'umkm/barokah-2.jpg',
                    'umkm/barokah-3.jpg',
                    'umkm/barokah-4.jpg',
                    'umkm/barokah-5.jpg'
                ]),
                'address' => 'Jl. Dahlia Kampung Dalam No. 20, RT 02/RW 02',
                'phone' => '081901234567',
                'whatsapp' => '081901234567',
                'email' => 'busanabarokah@gmail.com',
                'instagram' => '@busanabarokah',
                'facebook' => 'Konveksi Barokah',
                'website' => 'www.busanabarokah.com',
                'products' => 'Gamis, Hijab, Mukena, Baju Koko, Sarung, Kerudung, Jilbab, Abaya',
                'capital' => 75000000.00,
                'monthly_revenue' => 22000000.00,
                'employee_count' => 12,
                'established_date' => '2017-04-10',
                'license_number' => 'IUI/008/2017',
                'is_active' => true,
            ],
            [
                'business_name' => 'Warung Kopi Robusta Asli',
                'owner_name' => 'Bapak Irwan Setiawan',
                'nik' => '1471234567890009',
                'category' => 'kuliner',
                'description' => 'Warung kopi yang menyajikan kopi robusta asli dengan berbagai varian olahan dan camilan tradisional. Menggunakan biji kopi pilihan dari petani lokal.',
                'featured_image' => 'umkm/warung-kopi.jpg',
                'product_images' => json_encode([
                    'umkm/kopi-1.jpg',
                    'umkm/kopi-2.jpg',
                    'umkm/kopi-3.jpg'
                ]),
                'address' => 'Jl. Raya Kampung Dalam No. 30, RT 01/RW 03',
                'phone' => '082012345678',
                'whatsapp' => '082012345678',
                'email' => 'robustaasli@gmail.com',
                'instagram' => '@robustaasli',
                'facebook' => 'Warung Kopi Robusta Asli',
                'website' => null,
                'products' => 'Kopi Robusta, Kopi Susu, Pisang Goreng, Roti Bakar, Teh Tarik, Gorengan, Kue Tradisional',
                'capital' => 30000000.00,
                'monthly_revenue' => 9500000.00,
                'employee_count' => 4,
                'established_date' => '2019-06-05',
                'license_number' => 'SIUP/009/2019',
                'is_active' => true,
            ],
            [
                'business_name' => 'Pabrik Es Batu Dingin Segar',
                'owner_name' => 'Bapak Sutomo',
                'nik' => '1471234567890010',
                'category' => 'perdagangan',
                'description' => 'Pabrik es batu yang melayani kebutuhan es untuk warung, restoran, dan acara-acara dengan kualitas higienis. Menggunakan air bersih dan proses produksi yang steril.',
                'featured_image' => 'umkm/pabrik-es.jpg',
                'product_images' => json_encode([
                    'umkm/es-1.jpg',
                    'umkm/es-2.jpg'
                ]),
                'address' => 'Jl. Industri Kampung Dalam No. 5, RT 03/RW 03',
                'phone' => '082123456789',
                'whatsapp' => '082123456789',
                'email' => 'dinginsegar@gmail.com',
                'instagram' => '@dinginsegar_es',
                'facebook' => null,
                'website' => null,
                'products' => 'Es Batu Balok, Es Batu Kristal, Es Serut, Air Galon, Es Tube',
                'capital' => 80000000.00,
                'monthly_revenue' => 16000000.00,
                'employee_count' => 8,
                'established_date' => '2014-09-12',
                'license_number' => 'IUI/010/2014',
                'is_active' => true,
            ],
            [
                'business_name' => 'Laundry Express Bersih Wangi',
                'owner_name' => 'Ibu Sari Indah',
                'nik' => '1471234567890011',
                'category' => 'jasa',
                'description' => 'Layanan laundry kiloan dan satuan dengan pelayanan cepat, bersih, dan wangi menggunakan deterjen berkualitas. Melayani cuci reguler hingga dry cleaning.',
                'featured_image' => 'umkm/laundry-express.jpg',
                'product_images' => json_encode([
                    'umkm/laundry-1.jpg',
                    'umkm/laundry-2.jpg'
                ]),
                'address' => 'Jl. Kenanga Kampung Dalam No. 18, RT 02/RW 03',
                'phone' => '082234567890',
                'whatsapp' => '082234567890',
                'email' => 'bersihwangi@gmail.com',
                'instagram' => '@laundryexpress_bw',
                'facebook' => 'Laundry Express Bersih Wangi',
                'website' => null,
                'products' => 'Cuci Kiloan, Cuci Satuan, Setrika, Dry Clean, Cuci Sepatu, Cuci Karpet, Cuci Boneka',
                'capital' => 40000000.00,
                'monthly_revenue' => 11000000.00,
                'employee_count' => 5,
                'established_date' => '2020-03-22',
                'license_number' => 'SIUP/011/2020',
                'is_active' => true,
            ],
            [
                'business_name' => 'Budidaya Ikan Lele Maju Jaya',
                'owner_name' => 'Bapak Agus Salim',
                'nik' => '1471234567890012',
                'category' => 'pertanian',
                'description' => 'Budidaya ikan lele dengan sistem bioflok yang menghasilkan ikan lele berkualitas tinggi dan ramah lingkungan. Menggunakan teknologi modern untuk hasil optimal.',
                'featured_image' => 'umkm/budidaya-lele.jpg',
                'product_images' => json_encode([
                    'umkm/lele-1.jpg',
                    'umkm/lele-2.jpg',
                    'umkm/lele-3.jpg'
                ]),
                'address' => 'Dusun Maju RT 02/RW 03',
                'phone' => '082345678901',
                'whatsapp' => '082345678901',
                'email' => 'lelemaju@gmail.com',
                'instagram' => '@budidayalelemaju',
                'facebook' => 'Budidaya Lele Maju Jaya',
                'website' => null,
                'products' => 'Ikan Lele Konsumsi, Bibit Lele, Pakan Ikan, Pupuk Organik, Ikan Lele Asap',
                'capital' => 55000000.00,
                'monthly_revenue' => 14500000.00,
                'employee_count' => 6,
                'established_date' => '2018-11-08',
                'license_number' => 'SIUP/012/2018',
                'is_active' => true,
            ],
            [
                'business_name' => 'Toko Online Gadget Smart',
                'owner_name' => 'Bapak Rizki Pratama',
                'nik' => '1471234567890013',
                'category' => 'teknologi',
                'description' => 'Toko online yang menjual berbagai gadget, aksesoris handphone, dan perangkat teknologi terkini dengan harga kompetitif. Melayani penjualan online dan offline.',
                'featured_image' => 'umkm/gadget-smart.jpg',
                'product_images' => json_encode([
                    'umkm/gadget-1.jpg',
                    'umkm/gadget-2.jpg',
                    'umkm/gadget-3.jpg'
                ]),
                'address' => 'Jl. Teknologi Kampung Dalam No. 7, RT 01/RW 01',
                'phone' => '082456789012',
                'whatsapp' => '082456789012',
                'email' => 'gadgetsmart@gmail.com',
                'instagram' => '@gadgetsmart_kd',
                'facebook' => 'Gadget Smart KD',
                'website' => 'www.gadgetsmart.com',
                'products' => 'Handphone, Aksesoris HP, Power Bank, Earphone, Speaker, Smartwatch, Laptop',
                'capital' => 100000000.00,
                'monthly_revenue' => 25000000.00,
                'employee_count' => 4,
                'established_date' => '2022-01-15',
                'license_number' => 'OSS/013/2022',
                'is_active' => true,
            ],
            [
                'business_name' => 'Catering Nusantara Rasa',
                'owner_name' => 'Ibu Fitri Handayani',
                'nik' => '1471234567890014',
                'category' => 'kuliner',
                'description' => 'Layanan catering untuk berbagai acara dengan menu masakan nusantara yang lezat dan higienis. Melayani acara pernikahan, syukuran, dan acara kantor.',
                'featured_image' => 'umkm/catering-nusantara.jpg',
                'product_images' => json_encode([
                    'umkm/catering-1.jpg',
                    'umkm/catering-2.jpg',
                    'umkm/catering-3.jpg',
                    'umkm/catering-4.jpg'
                ]),
                'address' => 'Jl. Nusantara Kampung Dalam No. 22, RT 03/RW 01',
                'phone' => '082567890123',
                'whatsapp' => '082567890123',
                'email' => 'nusantararasa@gmail.com',
                'instagram' => '@nusantararasa_catering',
                'facebook' => 'Catering Nusantara Rasa',
                'website' => null,
                'products' => 'Paket Prasmanan, Nasi Box, Snack Box, Tumpeng, Menu Tradisional, Kue Basah, Kue Kering',
                'capital' => 65000000.00,
                'monthly_revenue' => 20000000.00,
                'employee_count' => 10,
                'established_date' => '2019-12-01',
                'license_number' => 'SIUP/014/2019',
                'is_active' => true,
            ],
            [
                'business_name' => 'Jasa Fotografi Moment Indah',
                'owner_name' => 'Bapak Dedi Kurniawan',
                'nik' => '1471234567890015',
                'category' => 'jasa',
                'description' => 'Jasa fotografi profesional untuk berbagai acara seperti pernikahan, ulang tahun, dan dokumentasi kegiatan. Menggunakan peralatan modern dan tim berpengalaman.',
                'featured_image' => 'umkm/fotografi-moment.jpg',
                'product_images' => json_encode([
                    'umkm/foto-1.jpg',
                    'umkm/foto-2.jpg',
                    'umkm/foto-3.jpg'
                ]),
                'address' => 'Jl. Seni Kampung Dalam No. 14, RT 02/RW 01',
                'phone' => '082678901234',
                'whatsapp' => '082678901234',
                'email' => 'momentindah@gmail.com',
                'instagram' => '@momentindah_photo',
                'facebook' => 'Moment Indah Photography',
                'website' => 'www.momentindah.com',
                'products' => 'Foto Wedding, Foto Prewedding, Foto Keluarga, Video Dokumenter, Foto Produk, Cetak Foto',
                'capital' => 85000000.00,
                'monthly_revenue' => 18500000.00,
                'employee_count' => 5,
                'established_date' => '2020-07-10',
                'license_number' => 'SIUP/015/2020',
                'is_active' => true,
            ]
        ];

        foreach ($umkmData as $umkm) {
            Umkm::create($umkm);
        }
    }
}
